# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Markers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('lat', models.FloatField(default=0)),
                ('log', models.FloatField(default=0)),
            ],
        ),
    ]
