# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxify', '0002_markers'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
